/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.joguinho;

import javax.swing.JOptionPane;

/**
 *
 * @author Evandro Borzi Marques
 */
public class jokempo extends javax.swing.JFrame {
    int jogador;

    public void jogar() {
        int sorteio = (int) (Math.random() * 3 + 1);
        switch (sorteio) {
            case 1:
                lblPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_hand-peace-o_1608374.png")));
                break;
            case 2:
                lblPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_hand-rock-o_1608372.png")));
                break;
            case 3:
                lblPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_hand-stop-o_1608369.png")));
                break;

        }
        if (jogador != sorteio) {
            if (((jogador == 1) && (sorteio == 2)) || ((jogador == 2) && (sorteio == 3)) || ((jogador == 3) && (sorteio == 1))) {
                lblResultado.setText("VOCÊ PERDEU");
            } else {
                lblResultado.setText("VOCÊ GANHOU");
            }
        } else {
            lblResultado.setText("VOCÊ EMPATOU");
        }

    }


    /**
     * Creates new form jokempo
     */
    public jokempo() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPc = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        bntPedra = new javax.swing.JButton();
        btnPapel = new javax.swing.JButton();
        btnTesoura = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lblPc.setText("oponente");

        lblResultado.setText("resultado");

        bntPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_hand-rock-o_1608372.png"))); // NOI18N
        bntPedra.setText("pedra");
        bntPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPedraActionPerformed(evt);
            }
        });

        btnPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_hand-stop-o_1608369.png"))); // NOI18N
        btnPapel.setText("papel");
        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btnTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_hand-peace-o_1608374.png"))); // NOI18N
        btnTesoura.setText("tesoura ");
        btnTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesouraActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/sair.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblPc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntPedra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTesoura))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(lblPc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPedra)
                    .addComponent(btnPapel)
                    .addComponent(btnTesoura))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPedraActionPerformed
        // TODO add your handling code here:
        jogador = 2;
        jogar();
        //lblPc.setText(null);
        //lblResultado.setText(null);

        /* switch (sorteio + 1){
            case 1:
            lblResultado.setText("VOCÊ PERDEU");
            break;
            case 2:
            lblResultado.setText("VOCÊ EMPATOU");
            break;
            case 3:
            lblResultado.setText("VOCÊ GANHOU");
            break;
        }
        */
    }//GEN-LAST:event_bntPedraActionPerformed

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelActionPerformed
        // TODO add your handling code here:
        jogador = 3;
        jogar();
        //lblPc.setText(null);
        //lblResultado.setText(null);
        /*switch (sorteio + 1){
            case 1:
            lblResultado.setText("VOCÊ PERDEU");
            break;
            case 2:
            lblResultado.setText("VOCÊ GANHOU");
            break;
            case 3:
            lblResultado.setText("VOCÊ EMPATOU");
            break;
        }
        */
    }//GEN-LAST:event_btnPapelActionPerformed

    private void btnTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesouraActionPerformed
        // TODO add your handling code here:
        jogador = 1;
        jogar();
        // lblPc.setText(null);
        //lblResultado.setText(null);
        /*switch (sorteio + 1){
            case 1:
            lblResultado.setText("VOCÊ EMPATOU");
            break;
            case 2:
            lblResultado.setText("VOCÊ PERDEU");
            break;
            case 3:
            lblResultado.setText("VOCÊ GANHOU");
            break;
        }
        */
    }//GEN-LAST:event_btnTesouraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
	int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
        dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(jokempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(jokempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(jokempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(jokempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new jokempo().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPedra;
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnTesoura;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblPc;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
