/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.apps;

import br.com.jogo.cartas.SortearCarta;
import br.com.senac.alcxgas.CalculadoraFlex;
import br.com.senac.calculadora.Calculando;
import br.com.senac.calculo.converter;
import br.com.senac.carro.caravana;
import br.com.senac.imc.grafic;
import br.com.senac.jogo.dados;
import br.com.senac.joguinho.jokempo;
import br.com.senac.media.Calculomedia;
import br.com.senac.tabu.tabua;

/**
 *
 * @author Evandro Borzi Marques
 */
public class Intaplicativo extends javax.swing.JFrame {

    /**
     * Creates new form Intaplicativo
     */
    public Intaplicativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnescola = new javax.swing.JButton();
        btnimc = new javax.swing.JButton();
        btnalcoolgasolina = new javax.swing.JButton();
        btndado = new javax.swing.JButton();
        btncarta = new javax.swing.JButton();
        btnpedrapapel = new javax.swing.JButton();
        btntabuada = new javax.swing.JButton();
        btncalculadora = new javax.swing.JButton();
        btnconversao = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(730, 410));
        setMinimumSize(new java.awt.Dimension(730, 410));
        setPreferredSize(new java.awt.Dimension(730, 410));
        getContentPane().setLayout(null);

        btnescola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/Média escolar.png"))); // NOI18N
        btnescola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnescolaActionPerformed(evt);
            }
        });
        getContentPane().add(btnescola);
        btnescola.setBounds(20, 30, 100, 70);

        btnimc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/imc.png"))); // NOI18N
        btnimc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimcActionPerformed(evt);
            }
        });
        getContentPane().add(btnimc);
        btnimc.setBounds(170, 30, 97, 73);

        btnalcoolgasolina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/posto.png"))); // NOI18N
        btnalcoolgasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalcoolgasolinaActionPerformed(evt);
            }
        });
        getContentPane().add(btnalcoolgasolina);
        btnalcoolgasolina.setBounds(460, 30, 97, 73);

        btndado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/l.png"))); // NOI18N
        btndado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndadoActionPerformed(evt);
            }
        });
        getContentPane().add(btndado);
        btndado.setBounds(610, 30, 97, 73);

        btncarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/Baralho.png"))); // NOI18N
        btncarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncartaActionPerformed(evt);
            }
        });
        getContentPane().add(btncarta);
        btncarta.setBounds(540, 150, 97, 73);

        btnpedrapapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/jokenpo.png"))); // NOI18N
        btnpedrapapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpedrapapelActionPerformed(evt);
            }
        });
        getContentPane().add(btnpedrapapel);
        btnpedrapapel.setBounds(90, 150, 97, 73);

        btntabuada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/eu.png"))); // NOI18N
        btntabuada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntabuadaActionPerformed(evt);
            }
        });
        getContentPane().add(btntabuada);
        btntabuada.setBounds(250, 280, 97, 73);

        btncalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/Calculadora2.0.png"))); // NOI18N
        btncalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculadoraActionPerformed(evt);
            }
        });
        getContentPane().add(btncalculadora);
        btncalculadora.setBounds(50, 280, 97, 73);

        btnconversao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/conversor.png"))); // NOI18N
        btnconversao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconversaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnconversao);
        btnconversao.setBounds(460, 280, 97, 73);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/final.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(300, 150, 100, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/all/wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 728, 409);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnescolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnescolaActionPerformed
        // TODO add your handling code here:
        Calculomedia media = new Calculomedia();
        media.setVisible(true);
    }//GEN-LAST:event_btnescolaActionPerformed

    private void btnimcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimcActionPerformed
        // TODO add your handling code here:
        grafic codigo = new grafic();
        codigo.setVisible(true);
    }//GEN-LAST:event_btnimcActionPerformed

    private void btnconversaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconversaoActionPerformed
        // TODO add your handling code here:
        converter classe = new converter();
        classe.setVisible(true);
    }//GEN-LAST:event_btnconversaoActionPerformed

    private void btnalcoolgasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalcoolgasolinaActionPerformed
        // TODO add your handling code here:
        CalculadoraFlex calculadora = new CalculadoraFlex();
        calculadora.setVisible(true);
    }//GEN-LAST:event_btnalcoolgasolinaActionPerformed

    private void btncartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncartaActionPerformed
        // TODO add your handling code here:
	 SortearCarta sorteio = new SortearCarta();
         sorteio.setVisible(true);
    }//GEN-LAST:event_btncartaActionPerformed

    private void btncalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculadoraActionPerformed
        // TODO add your handling code here:
	Calculando Codigo = new Calculando();
	Codigo.setVisible(true);
    }//GEN-LAST:event_btncalculadoraActionPerformed

    private void btndadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndadoActionPerformed
        // TODO add your handling code here:
	 dados joguin = new dados();
	joguin.setVisible(true);
    }//GEN-LAST:event_btndadoActionPerformed

    private void btntabuadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntabuadaActionPerformed
        // TODO add your handling code here:
	tabua cltabu = new tabua();
	cltabu.setVisible(true);
    }//GEN-LAST:event_btntabuadaActionPerformed

    private void btnpedrapapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpedrapapelActionPerformed
        // TODO add your handling code here:
	jokempo jogoss = new jokempo();
	jogoss.setVisible(true);
    }//GEN-LAST:event_btnpedrapapelActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        caravana parcela = new caravana();
        parcela.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intaplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intaplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intaplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intaplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intaplicativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalcoolgasolina;
    private javax.swing.JButton btncalculadora;
    private javax.swing.JButton btncarta;
    private javax.swing.JButton btnconversao;
    private javax.swing.JButton btndado;
    private javax.swing.JButton btnescola;
    private javax.swing.JButton btnimc;
    private javax.swing.JButton btnpedrapapel;
    private javax.swing.JButton btntabuada;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
